version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
